# Generated by Django 5.2.4 on 2025-08-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='service_images/')),
                ('servicename', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('welding', 'Welding'), ('cableprovider', 'Cable Provider'), ('internet', 'Internet Service'), ('groceries', 'Groceries')], max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('is_approved', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['-id'],
            },
        ),
    ]
