# Generated by Django 5.2.4 on 2025-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0002_activitylog_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderr',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderr',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
