# Generated by Django 5.2.4 on 2025-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0003_serviceproviderr_approval_date_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='serviceproviderr',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]