# Generated by Django 5.2.4 on 2025-08-07 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0005_alter_serviceproviderr_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderr',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
