# Generated by Django 5.2.4 on 2025-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0006_alter_serviceproviderr_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderr',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
