# Generated by Django 5.2.4 on 2025-08-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0007_alter_serviceproviderr_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderr',
            name='date_joined',
        ),
    ]
