# Generated by Django 5.2.4 on 2025-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0008_remove_serviceproviderr_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderr',
            name='servicename',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('welding', 'Welder'), ('cableprovider', 'Cable Provider'), ('internet', 'Internet Service'), ('groceries', 'Groceries')], max_length=100),
        ),
    ]
