# Generated by Django 5.2.4 on 2025-08-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0009_alter_serviceproviderr_servicename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderr',
            name='servicename',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('welder', 'Welder'), ('cable', 'Cable Provider'), ('internet', 'Internet Service'), ('groceries', 'Groceries')], max_length=100),
        ),
    ]
